project:
  type: website
  output-dir: docs

website:
  title: "My Personal Website"
  navbar:
    left:
      - text: Home
        href: Home_page.qmd
      - text: About
        href: about.qmd
      - text: Example Analysis
        href: example-analysis.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    marginnote: true

editor: visual
execute:
  freeze: auto


    




  
